CREATE TABLE IF NOT EXISTS shopping_list (
    shopping_id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    item_name TEXT NOT NULL,
    item_price NUMERIC NOT NULL,
    item_category TEXT NOT NULL,
    checked BOOLEAN NOT NULL,
    date_added TIMESTAMP DEFAULT now() NOT NULL
);


DROP TYPE IF EXISTS grocery;
CREATE TYPE grocery as Enum (
    'Main',
    'Snack',
    'Lunch',
    'Breakfast'
);


